### ISSUE TITLE
Can't use the package in a browser

### ISSUE THREAD

**Issue by yjkimjunior** [snapshot-labs/snapshot.js#67]
### Expected behavior
Install snapshot.js in my frontend app and use it normally

### Actual behavior
Uncaught reference error BN is not defined

### Steps to reproduce the behavior
create-react-app demo
cd demo
npm i @snapshot-labs/snapshot.js
npm start

**Comment by bonustrack** [comment]
@yjkimjunior This was fixed in #69, can you try again?

**Comment by yjkimjunior** [comment]
The issue persists :/ 

Installing with `yarn add @snapshot-labs/snapshot.js@0.1.1` like in https://github.com/snapshot-labs/snapshot.js/packages/502404 will resolve to 0.1.0 not 0.1.1 and at runtime will result in the same issue as above so maybe the fix wasn't released?

Installing with `yarn add snapshot-labs/snapshot.js#master` fails to build with `Error: Cannot find module 'path/to/node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js'. Please verify that the package.json has a valid "main" entry`

**Comment by yjkimjunior** [comment]
@bonustrack @ChaituVR  wish I could be of more help...I made a minimal reproduction of the issue here https://github.com/yjkimjunior/repro

**Comment by bonustrack** [comment]
> the fix wasn't released?
@yjkimjunior Yes actually the new pkg was not published on NPM, i've just published it with the version 0.1.1, can you try again if it works for you?

**Comment by yjkimjunior** [comment]
seems to work now :) thank you once again

**Comment by yjkimjunior** [comment]
@bonustrack 

Argh, spoke too soon maybe.

The package not found issue is definitely fixed, however in another rollup issue it doesn't seem to export anything?

e.g. 

```

import snapshot from "@snapshot-labs/snapshot.js";

function App() {
  console.log(snapshot) // returns {}
  console.log(snapshot.strategies) // expected: { balancer: {}, etc... }; actual: returns undefined
}
```

I also tried to `import snapshot from @snapshot-labs/snapshot.js/dist/index` and other variations but says `Module not found`

**Comment by bonustrack** [comment]
@yjkimjunior I created another issue for it #70

**Comment by bonustrack** [comment]
@yjkimjunior It should be fixed in v0.1.2 can you test?

**Comment by yjkimjunior** [comment]
Nice! Seems to work well, I will try the full integration on our end and let you know. Happy New Year!

<img width="1179" alt="Screen Shot 2020-12-31 at 5 10 15 PM" src="https://user-images.githubusercontent.com/10432070/103417469-1af91180-4b8b-11eb-9132-584210a18a3a.png">
